// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwAApi-dNBxKHMkzMUvDNAoIYWJ2iNYlY',
    appId: '1:370582398094:web:7b55fea9f5b4f322af55df',
    messagingSenderId: '370582398094',
    projectId: 'champing-d26a9',
    authDomain: 'champing-d26a9.firebaseapp.com',
    storageBucket: 'champing-d26a9.appspot.com',
    measurementId: 'G-1YDJWQ6N87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSVyB6TlD0Ew6M9xsXdA8jXVgLV65Q8SE',
    appId: '1:370582398094:android:fcf9f0d46c22952baf55df',
    messagingSenderId: '370582398094',
    projectId: 'champing-d26a9',
    storageBucket: 'champing-d26a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBdISSml7KwwOo19BFbUk0yk7_YABQ260',
    appId: '1:370582398094:ios:e3fff8dbee060237af55df',
    messagingSenderId: '370582398094',
    projectId: 'champing-d26a9',
    storageBucket: 'champing-d26a9.appspot.com',
    androidClientId: '370582398094-mm3ciktbldhvu3f1emf092rqlqq5n15v.apps.googleusercontent.com',
    iosClientId: '370582398094-m7c9baq6k39nvgaanrptbgvajlti7728.apps.googleusercontent.com',
    iosBundleId: 'com.example.task2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBdISSml7KwwOo19BFbUk0yk7_YABQ260',
    appId: '1:370582398094:ios:e3fff8dbee060237af55df',
    messagingSenderId: '370582398094',
    projectId: 'champing-d26a9',
    storageBucket: 'champing-d26a9.appspot.com',
    androidClientId: '370582398094-mm3ciktbldhvu3f1emf092rqlqq5n15v.apps.googleusercontent.com',
    iosClientId: '370582398094-m7c9baq6k39nvgaanrptbgvajlti7728.apps.googleusercontent.com',
    iosBundleId: 'com.example.task2',
  );
}
